language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: WqwkXxoekY44mSkK+YzZtmsy51S+YWWzYC3/G0iKsIsxRJPUK2+8cAtukRGSNYnBP1HRpoxprCAXOd6DjVsm7tgpvwHsaBqBzMINnkYsQ49rwo2V/jVDemQiLW8N18US/O3sTfxTkSxvJRi0K+2vkXzsJ3cyEfiRUTu8CB68ax+CHgdp1ecSw64MKQ1XqUkZy/pC8A7UZCcSTJOfP8LOQYHna/1po2HR1HcEXHg955DEkqz1XmvbaJ12k4wv8ZDVM7XwiQt55cirZy+YgX6eYFKlfhZx7Q4H+RApXgHD+Y/YrN//29nHY+LXJyBUi4thFLzgU3RltWTpqo9NnktZNe9HYmqqIb0hatWjD0+cQQuF8VEw3stmcGctqYFHG/lg5PtrvZ3zgiB65F7dn2zpsC5A1Nt+yG8uHCzRZU21ZfnP9FgWnBtRchCcKY/LhLVmGWPsqg6ws0v0erf+15URV+qy/+sd3imADL0rI89llrt6+S6hCMiNsnsCKckAIzeKQYTMRaSRWXFfVDdXu4GO50/5yr00ikJrCMBK+3yAWTqPSmv0ixAyajuuj5PT6ve0nkSE+Al1/xjPSIFX5XY3+D3PHDInrHZI046Ez9AK5twEG/vL7YsSptdlOmd0OFWch3kYdV+y3WwliR1xLCRJd+r1awN2beAKvn04gGMS+Fg=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-express
